/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testebanco;

/**
 *
 * @author 280800093
 */
public class TelaPrincipal extends javax.swing.JFrame {

    
    private Double valorTotal;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.valorTotal = 0.0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCaneta = new javax.swing.JButton();
        btLapis = new javax.swing.JButton();
        btBorracha = new javax.swing.JButton();
        btSulfite = new javax.swing.JButton();
        btCaderno = new javax.swing.JButton();
        btPasta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbValorTotal = new javax.swing.JLabel();
        btLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btCaneta.setText("Caneta");
        btCaneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCanetaActionPerformed(evt);
            }
        });

        btLapis.setText("Lapis");
        btLapis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLapisActionPerformed(evt);
            }
        });

        btBorracha.setText("Borracha");
        btBorracha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBorrachaActionPerformed(evt);
            }
        });

        btSulfite.setText("Sulfite");
        btSulfite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSulfiteActionPerformed(evt);
            }
        });

        btCaderno.setText("Caderno");
        btCaderno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadernoActionPerformed(evt);
            }
        });

        btPasta.setText("Pasta");
        btPasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPastaActionPerformed(evt);
            }
        });

        jLabel1.setText("Valor Total: ");

        lbValorTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbValorTotal.setText("0.00");
        lbValorTotal.setToolTipText("");

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btCaderno)
                        .addComponent(btBorracha)
                        .addComponent(btCaneta, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel1))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btLapis)
                    .addComponent(btSulfite)
                    .addComponent(btPasta)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbValorTotal)
                        .addGap(8, 8, 8)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btLimpar)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCaneta)
                    .addComponent(btLapis))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBorracha)
                    .addComponent(btSulfite))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCaderno)
                    .addComponent(btPasta))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbValorTotal))
                .addGap(18, 18, 18)
                .addComponent(btLimpar)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCanetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCanetaActionPerformed
        // TODO add your handling code here:
        
        this.valorTotal+=2.00;
        lbValorTotal.setText(valorTotal.toString());
        
    }//GEN-LAST:event_btCanetaActionPerformed

    private void btBorrachaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBorrachaActionPerformed
        // TODO add your handling code here:
        this.valorTotal+=1.25;
        lbValorTotal.setText(valorTotal.toString());
    }//GEN-LAST:event_btBorrachaActionPerformed

    private void btCadernoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadernoActionPerformed
        // TODO add your handling code here:
        this.valorTotal+=10.25;
        lbValorTotal.setText(valorTotal.toString());
    }//GEN-LAST:event_btCadernoActionPerformed

    private void btLapisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLapisActionPerformed
        // TODO add your handling code here:
        this.valorTotal+=1.25;
        lbValorTotal.setText(valorTotal.toString());
    }//GEN-LAST:event_btLapisActionPerformed

    private void btSulfiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSulfiteActionPerformed
        // TODO add your handling code here:
        this.valorTotal+=0.25;
        lbValorTotal.setText(valorTotal.toString());
    }//GEN-LAST:event_btSulfiteActionPerformed

    private void btPastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPastaActionPerformed
        // TODO add your handling code here:
        this.valorTotal+=15.50;
        lbValorTotal.setText(valorTotal.toString());
    }//GEN-LAST:event_btPastaActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        this.valorTotal=0.0;
        lbValorTotal.setText(valorTotal.toString());
    }//GEN-LAST:event_btLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBorracha;
    private javax.swing.JButton btCaderno;
    private javax.swing.JButton btCaneta;
    private javax.swing.JButton btLapis;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPasta;
    private javax.swing.JButton btSulfite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbValorTotal;
    // End of variables declaration//GEN-END:variables
}
